name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      statuses: write
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Convert test script line endings
        run: dos2unix ./scripts/test.py

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag my-local-image:latest

      - name: Run tests inside the Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            my-local-image:latest \
            ./scripts/test.sh

      - name: Perm issue fix
        if: success() || failure()
        run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: bin/junit_results.xml
          reporter: java-junit
          fail-on-error: false

